# completion.zsh — tab completion.

# Homebrew-installed completions (git, gh, docker, zsh-completions, …).
if (( $+commands[brew] )); then
  fpath=("$(brew --prefix)/share/zsh/site-functions" $fpath)
fi

# compinit is slow when it re-audits every start; do the full check at most
# once a day and trust the cache (-C) otherwise.
autoload -Uz compinit
() {
  setopt localoptions extendedglob   # for the (#q…) age qualifier below
  if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
    compinit        # dump older than 24h (or missing): full check, rewrite it
  else
    compinit -C     # fresh dump: trust it, skip the audit
  fi
}

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'   # case-insensitive
zstyle ':completion:*' menu select                        # arrow-key menu

# Completions generated by the tools themselves, when installed.
(( $+commands[kubectl] ))  && source <(kubectl completion zsh)
(( $+commands[talosctl] )) && source <(talosctl completion zsh)
