# completion.zsh — tab completion. Sourced from zshrc (interactive shells).

typeset -U fpath   # no duplicate entries, however often this is sourced

# Homebrew-installed completions. $HOMEBREW_PREFIX comes from `brew shellenv`
# in zprofile (cheaper than running `brew --prefix` on every start).
#   site-functions   completions that formulae ship (git, gh, docker, …)
#   zsh-completions  the zsh-completions formula's collection, kept separately
if [[ -n "${HOMEBREW_PREFIX:-}" ]]; then
  for d in "$HOMEBREW_PREFIX/share/zsh-completions" "$HOMEBREW_PREFIX/share/zsh/site-functions"; do
    [[ -d "$d" ]] && fpath=("$d" $fpath)
  done
  unset d
fi

# compinit is slow when it re-audits every start; do the full check at most
# once a day and trust the cache (-C) otherwise.
autoload -Uz compinit
() {
  setopt localoptions extendedglob   # for the (#q…) age qualifier below
  if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
    compinit        # dump older than 24h: full check, rewrite it
  else
    compinit -C     # fresh (or missing) dump: skip the audit; a missing dump is still written
  fi
}

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'   # case-insensitive
zstyle ':completion:*' menu select                        # arrow-key menu

# Completions generated by the tools themselves, when installed. (Each costs a
# process at start-up; drop the line if you don't use the tool.)
(( $+commands[kubectl] ))  && source <(kubectl completion zsh)
(( $+commands[talosctl] )) && source <(talosctl completion zsh)
